name: Approval Made

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approved:
    if: ${{ github.event.review.state == 'approved' && contains(github.event.pull_request.labels.*.name, 'beta-environment') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved and contains the beta-environment label"
