name: Approval Made

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - run: echo ${{ toJson(github) }}
