name: Beta Environment

on:
  pull_request_review:
    types:
      - submitted

jobs:  
  beta-environment-skipped:
    if: |
      "!contains(github.event.pull_request.labels.*.name, 'beta-environment')" &&
      github.event.review.state != 'approved' &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.draft == false
        run: echo "Needs to be a Draft PR to build to beta-environment"
      - if: "!contains(github.event.pull_request.labels.*.name, 'beta-environment')"
        run: echo "Need to have 'beta-environment' label to build to beta-environment"
      - if: github.event.review.state != 'approved'
        run: echo "Need to have an 'approved' pr to build out"
  beta-environment-build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'beta-environment') &&
      github.event.review.state == 'approved' &&
      github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "This DRAFT PR was approved and has beta-environment label"
      - run: echo "${{ toJson(github) }}"
