name: Beta Environment

on:
  pull_request:
    types:
      - closed
  pull_request_review:
    types:
      - submitted

jobs:  
  beta-environment-skipped:
    if: |
      ${{ !contains(github.event.pull_request.labels.*.name, 'beta-environment') }} ||
      github.event.review.state != 'approved' ||
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.draft == false
        run: echo "Needs to be a Draft PR to build to beta-environment"
      - if: "!contains(github.event.pull_request.labels.*.name, 'beta-environment')"
        run: echo "Need to have 'beta-environment' label to build to beta-environment"
      - if: github.event.review.state != 'approved'
        run: echo "Need to have an 'approved' pr to build out"
      - run: echo "${{ toJson(github) }}"
  beta-environment-destroy:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.state.closed == true
      run: echo "Need to destroy the beta-environment"
      # this job will only run if the PR has been merged
      - if: github.event.pull_request.merged == true
        run: |
          echo PR #${{ github.event.number }} has been merged
      # this job will only run if the PR has been closed without being merged
      - if: github.event.pull_request.merged == false
        run: |
          echo PR #${{ github.event.number }} has been closed without being merged
      - run: echo "${{ toJson(github) }}"

  beta-environment-build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'beta-environment') &&
      github.event.review.state == 'approved' &&
      github.event.pull_request.draft == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "This DRAFT PR was approved and has beta-environment label"
      - run: echo "${{ toJson(github) }}"
