name: Beta Environment

on:
  pull_request:
    types:
      - closed
      - unlabeled
  pull_request_review:
    types:
      - submitted

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.get-pr-number.outputs.pr_number }}
    steps:
      - name: Get PR number
        id: get-pr-number
        shell: bash
        run: |
          PR_FROM_EVENT=${{ github.event.number }}
          PR_FROM_REF=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          PR=${PR_FROM_REF:-$PR_FROM_EVENT}
          echo "pr_number=${PR}" >> $GITHUB_OUTPUT
      - name: (debug)
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo "github.ref: ${{ github.ref }}"
          echo "toJSON(github.event.inputs): ${{ toJSON(github.event.inputs) }}"
          echo "toJSON(inputs): ${{ toJSON(inputs) }}"

  beta-environment-build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'beta-environment') &&
      github.event.review.state == 'approved' &&
      github.event.pull_request.draft == true
    needs: [get-info]
    runs-on: ubuntu-latest
    steps:
      - name: 'Ref'
        run: echo ${{ github.head_ref }}

  beta-environment-remove:
    # This will run if it's closed, merged, or beta tag is removed.
    if: github.event.pull_request.state == 'closed' || (github.event.action == 'unlabeled' && !contains(github.event.pull_request.labels.*.name, 'beta-environment'))
    runs-on: ubuntu-latest
    needs: [get-info]
    steps:
      - name: 'Ref'
        run: echo ${{ github.head_ref }}
      - name: 'Ref on conditioned on closed'
        run: echo ${{ github.event.pull_request.state == 'closed' && 'master' || github.head_ref}}
