name: Lint Commit Messages
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  always:
    runs-on: ubuntu-latest
    steps:
      - name: (debug) github.event.action
        run: echo "${{ toJSON(github.event.action) }}"
      - name: (debug) github.event_name
        run: echo "${{ github.event_name }}"
      - name: (debug) github.event
        run: echo "${{ toJSON(github.event) }}"
      - name: (debug) github
        run: echo "${{ toJSON(github) }}"

  updated:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && github.event.action != 'closed'
    steps:
      - name: (debug) github.event.action
        run: echo "${{ toJSON(github.event.action) }}"
      - name: (debug) should build and run
        run: echo "should build and run"

  conditional-step:
    runs-on: ubuntu-latest
    steps:
      - name: (debug) github.event.action
        run: echo "${{ toJSON(github.event.action) }}"
      - name: (debug) should build and run always
        run: echo "should build and run always"
      - name: (debug) should build and run on != closed
        if: github.event.action != 'closed'
        run: echo "should build and run on != closed"
      - name: (debug) should build and run on == closed
        if: github.event.action == 'closed'
        run: echo "should build and run on == closed"

  closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: (debug) github.event.action
        run: echo "${{ toJSON(github.event.action) }}"
      - name: (debug) should tear down
        run: echo "should tear down"
