name: Lint Commit Messages
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "*/1 20-21 * * 1-5"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: (debug) github.event_name
        run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3
