name: Lint Commit Messages
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, closed]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: (debug) github.event
        run: echo "${{ toJSON(github.event) }}"
      - name: (debug) github.event.action
        run: echo "${{ toJSON(github.event.action) }}"
      - name: (debug) github.event_name
        run: echo "${{ github.event_name }}"
      - name: (debug) github
        run: echo "${{ toJSON(github) }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3
