name: Deploy on push to master
on: push

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      current-tag: ${{ steps.get-latest-image-version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create git short hash tag
        id: get-latest-image-version
        shell: bash
        run: |
          echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  deploy-serverless:
    needs: [get-version]
    uses: ./.github/workflows/deploy-serverless.yml
    with:
      image-tag: ${{ needs.get-version.outputs.current-tag }}
      services: '["jobs", "public-api"]'
      regions: '["us-east-1", "us-east-2"]'
      stage: staging
    secrets:
      encryption-secret: Foobar-Encryption-Secret # TODO grab from github secrets
    #   aws-secret-access-key: ${{ secrets.GH_USER_SECRET }}
    #   gh-packages-token: ${{ secrets.PACKAGES_ACCESS_TOKEN }}

  alert-build-channel:
    runs-on: ubuntu-latest
    needs: [get-version, deploy-serverless]

    steps:
      - run: echo "Should message that build is complete"
