name: Deploy manually

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to send traffic to
        options:
          - production
          - sandbox
      color:
        type: choice
        description: Environment to send traffic to
        default: green
        options:
          - blue
          - green

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: (debug) github.ref
        run: echo "${{ toJSON(github.ref) }}"
      - name: (debug) github.head_ref
        run: echo "${{ toJSON(github.head_ref) }}"
      - name: (debug) github.ref_name
        run: echo "${{ github.ref_name }}"
      - name: (debug) github.event_name
        run: echo "${{ github.event_name }}"
      - name: (debug) github.ref_type
        run: echo "${{ toJSON(github.ref_type) }}"
      - name: (debug) github.event.inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      - name: (debug) inputs
        run: echo "${{ toJSON(inputs) }}"

  deploy-production:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    steps:
      - run: |
          echo "Running production with color ${{ github.event.inputs.color }}"

  deploy-sandbox:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'sandbox'
    steps:
      - run: |
          echo "Running sandbox with color ${{ github.event.inputs.color }}"
