on: push

name: Jira Example

jobs:
  jira:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: AA
        issuetype: Story
        summary: |
          Test: evaluate dependabot alerts for ${{ github.repository }}
        description: |
          Run `yarn why <packageName>` to see where the package came from.
          Add the `--prod` flag to verify if it's something in the prod dependencies
        fields: '{"priority":{"name":"High","id":"2","iconUrl":"https://atomicfi.atlassian.net/images/icons/priorities/high.svg"},"labels":["Security"]}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
